### ISSUE TITLE
Wrong epoch display

### ISSUE THREAD

**Issue by MicheleCeresoli** [JuliaSpaceMissionDesign/Tempo.jl#18]
The displayed epoch is sometimes wrong, despite the actual value is computed correctly:

```julia
julia> ep = Epoch(20, TT)
2000-01-01T12:00:20.0000 TT

julia> ep1 = ep + 1
2000-01-01T12:00:20.10000 TT

julia> value(ep1)
21
```

**Comment by andreapasquale94** [comment]
Again? This was solved some time ago when still in gitlab, will double check it again.
