### ISSUE TITLE
handle day with leap second?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaSpaceMissionDesign/Tempo.jl#3]
currently
```
function fd2hms(fd::Number)
    secinday = fd * 86400.0
    if secinday < 0 || secinday > 86400
```

**Comment by andreapasquale94** [comment]
Hi @JeffreySarnoff, yes the library is capable to handle transformations including leapseconds. However these are handled at an higher level of abstraction than the function you mention.

Please wait for the release of the package documentation for more details (later this week).
